name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Decode FIRESTORE_KEY and GCP_KEY
      env:
        FIRESTORE_KEY_ENCODED: ${{ secrets.FIRESTORE_KEY_Decode }}
        GCP_KEY_ENCODED: ${{ secrets.GCP_KEY_Decode }}
      run: |
        echo "FIRESTORE_KEY=$(echo "$FIRESTORE_KEY_ENCODED" | base64 -d)" >> $GITHUB_ENV
        echo "GCP_KEY=$(echo "$GCP_KEY_ENCODED" | base64 -d)" >> $GITHUB_ENV

    - name: Authenticate GCloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ env.GCP_KEY_Decode }}
    
    - name: Setup GCloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: takes-two-to-fwango
        service_account_key: ${{ env.GCP_KEY_Decode }}
        export_default_credentials: true
        
    - name: Trigger Google Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml --substitutions=_FIRESTORE_KEY=${{ env.FIRESTORE_KEY_Decode }}

    - name: Deploy to App Engine
      run: |
        gcloud app deploy

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy t22f --image gcr.io/takes-two-to-fwango/image-1:t22f --platform managed --region europe-west1 --allow-unauthenticated



# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - test
#   pull_request:
#     branches:
#       - test

# jobs:
#   build_and_test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2
      
#       - name: Install Dependencies
#         run: npm install

#       - name: Run Tests
#         run: npm test

#   check_commit_date:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2
      
#       - name: Check Last Commit Date
#         run: |
#           COMMIT_DATE=$(git log -1 --pretty=format:%cd)
#           echo "Last commit date: $COMMIT_DATE"

#   check_test_success:
#     needs: build_and_test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Confirm Tests Success
#         run: echo "Tests were successful!"
