name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # ou la branche de votre choix

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
    
#     - name: Authenticate GCloud
#       uses: google-github-actions/auth@v0.4.0
#       with:
#         credentials_json: ${{ secrets.GCP_KEY }}

#     - name: Set up Cloud SDK
#       uses: google-github-actions/setup-gcloud@v1
#       with:
#         service_account_key: ${{ secrets.GCP_KEY }}
#         project_id: takes-two-to-fwango
#         export_default_credentials: true

#     - name: Authenticate Docker to GCR
#       run: |
#         echo '${{ secrets.GCP_KEY }}' | docker login -u _json_key --password-stdin https://gcr.io

#     - name: Build and Push Docker image
#       run: |
#         docker build -t gcr.io/takes-two-to-fwango/t22f .
#         docker push gcr.io/takes-two-to-fwango/t22f

#     - name: Deploy to Cloud Run
#       run: |
#         gcloud run deploy t22f --image gcr.io/takes-two-to-fwango/t22f --platform managed --allow-unauthenticated --project=takes-two-to-fwango --region europe-west1


# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - test
#   pull_request:
#     branches:
#       - test

# jobs:
#   build_and_test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2
      
#       - name: Install Dependencies
#         run: npm install

#       - name: Run Tests
#         run: npm test

#   check_commit_date:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2
      
#       - name: Check Last Commit Date
#         run: |
#           COMMIT_DATE=$(git log -1 --pretty=format:%cd)
#           echo "Last commit date: $COMMIT_DATE"

#   check_test_success:
#     needs: build_and_test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Confirm Tests Success
#         run: echo "Tests were successful!"
