name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Authenticate GCloud
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: takes-two-to-fwango
        export_default_credentials: true

    - name: Authenticate Docker to GCR
      run: |
        echo '${{ secrets.GCP_KEY }}' | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and Push Docker image
      # env:
      #   FIRESTORE_KEY: ${{ secrets.FIRESTORE_KEY }}
      #   GCP_KEY: ${{ secrets.GCP_KEY }}
      run: |
        IMAGE_TAG=$(date +"%Y%m%d%H%M%S")
        docker build -t t22f:$IMAGE_TAG .
        docker tag t22f:$IMAGE_TAG gcr.io/takes-two-to-fwango/t22f:$IMAGE_TAG
        docker push gcr.io/takes-two-to-fwango/t22f:$IMAGE_TAG


    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy t22f --image gcr.io/takes-two-to-fwango/t22f --platform managed --allow-unauthenticated --project=takes-two-to-fwango --region europe-west1

