name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # - name: Run google-github-actions/auth
    #   uses: google-github-actions/auth@v0.4.0
    #   with:
    #     credentials_json: ${{ secrets.GCP_KEY }}
    #     create_credentials_file: true
    #     access_token_lifetime: 3600s
    #     access_token_scopes: https://www.googleapis.com/auth/cloud-platform
    #     id_token_include_email: false
    #   env:
    #     NODE_OPTIONS: --max-old-space-size=4096 # Définit la taille maximale du tas à 4 Go (ajustez selon vos besoins)
    
  
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: takes-two-to-fwango
        export_default_credentials: true

    - name: Authenticate Docker to GCR
      run: |
        echo ${{ secrets.GCP_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

    - name : Creating .env file
      run: |
        touch .env
        echo FIRESTORE_KEY=${{ secrets.FIRESTORE_KEY }} >> .env
        echo GCP_KEY=${{ secrets.GCP_KEY }} >> .env 

    - name: Build and Push Docker image
      env:
        FIRESTORE_KEY: ${{ secrets.FIRESTORE_KEY }}
        GCP_KEY: ${{ secrets.GCP_KEY }}
      run: |
        IMAGE_TAG=$(date +"%Y%m%d%H%M%S")
        docker build -t t22f:$IMAGE_TAG .
        docker tag t22f:$IMAGE_TAG gcr.io/takes-two-to-fwango/t22f:$IMAGE_TAG
        docker push gcr.io/takes-two-to-fwango/t22f:$IMAGE_TAG


    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy t22f --image gcr.io/takes-two-to-fwango/t22f --platform managed --allow-unauthenticated --project=takes-two-to-fwango --region europe-west1

